web:
  bindAddress: "0.0.0.0"
  port: 8080
  webDirectory: 

database:
  storage: mongodb
  metrics: influxdb

databases:
  - name: mongodb
    database: mydb
    uri: "mongodb+srv://<username>:<password>@<hostname>/?retryWrites=true&w=majority"
  
  - name: influxdb
    database: mydb
    uri: http://localhost:9999

logger:
  level: DEBUG
  console: true