package mycontroller

// Entities
const (
	EntGateway        = "gateway"
	EntNode           = "node"
	EntSensor         = "sensor"
	EntSensorVariable = "SensorVariable"
)

// Commands
const (
	CmdPresentation = "C_PRESENTATION"
	CmdSet          = "C_SET"
	CmdRequest      = "C_REQUEST"
	CmdInternal     = "C_INTERNAL"
	CmdStream       = "C_STREAM"
)

// Sensors
const (
	SenAirQuality      = "S_AIR_QUALITY"
	SenBarometric      = "S_BAROMETRIC"
	SenBinary          = "S_BINARY"
	SenColorSensor     = "S_COLOR_SENSOR"
	SenCover           = "S_COVER"
	SenCustom          = "S_CUSTOM"
	SenDistance        = "S_DISTANCE"
	SenDoor            = "S_DOOR"
	SenDust            = "S_DUST"
	SenGas             = "S_GAS"
	SenGPS             = "S_GPS"
	SenHeater          = "S_HEATER"
	SenHumidity        = "S_HUMIDITY"
	SenHVAC            = "S_HVAC"
	SenInfo            = "S_INFO"
	SenIR              = "S_IR"
	SenLight           = "S_LIGHT"
	SenLock            = "S_LOCK"
	SenMoisture        = "S_MOISTURE"
	SenMotion          = "S_MOTION"
	SenMultimeter      = "S_MULTIMETER"
	SenPower           = "S_POWER"
	SenRain            = "S_RAIN"
	SenRGBLight        = "S_RGB_LIGHT"
	SenRGBWLight       = "S_RGBW_LIGHT"
	SenSceneController = "S_SCENE_CONTROLLER"
	SenSmoke           = "S_SMOKE"
	SenSound           = "S_SOUND"
	SenSprinkler       = "S_SPRINKLER"
	SenTemperature     = "S_TEMPERATURE"
	SenUV              = "S_UV"
	SenVibration       = "S_VIBRATION"
	SenWater           = "S_WATER"
	SenWaterLeak       = "S_WATER_LEAK"
	SenWaterQuality    = "S_WATER_QUALITY"
	SenWeight          = "S_WEIGHT"
	SenWind            = "S_WIND"
)

// Sensors data
const (
	VarArmed            = "V_ARMED"
	VarCurrent          = "V_CURRENT"
	VarDirection        = "V_DIRECTION"
	VarDistance         = "V_DISTANCE"
	VarDown             = "V_DOWN"
	VarEC               = "V_EC"
	VarFlow             = "V_FLOW"
	VarForecast         = "V_FORECAST"
	VarGust             = "V_GUST"
	VarHeater           = "V_HEATER"
	VarHumidity         = "V_HUMIDITY"
	VarHVACFlowMode     = "V_HVAC_FLOW_MODE"
	VarHVACFlowState    = "V_HVAC_FLOW_STATE"
	VarHVACSetpointCool = "V_HVAC_SETPOINT_COOL"
	VarHVACSetpointHeat = "V_HVAC_SETPOINT_HEAT"
	VarHVACSpeed        = "V_HVAC_SPEED"
	VarID               = "V_ID"
	VarImpedance        = "V_IMPEDANCE"
	VarIRReceive        = "V_IR_RECEIVE"
	VarIRRecord         = "V_IR_RECORD"
	VarIRSend           = "V_IR_SEND"
	VarKwh              = "V_KWH"
	VarLevel            = "V_LEVEL"
	VarLightLevel       = "V_LIGHT_LEVEL"
	VarLockStatus       = "V_LOCK_STATUS"
	VarORP              = "V_ORP"
	VarPercentage       = "V_PERCENTAGE"
	VarPH               = "V_PH"
	VarPosition         = "V_POSITION"
	VarPowerFactor      = "V_POWERFACTOR"
	VarPressure         = "V_PRESSURE"
	VarRain             = "V_RAIN"
	VarRainrate         = "V_RAINRATE"
	VarRGB              = "V_RGB"
	VarRGBW             = "V_RGBW"
	VarSceneOff         = "V_SCENE_OFF"
	VarSceneOn          = "V_SCENE_ON"
	VarStatus           = "V_STATUS"
	VarStop             = "V_STOP"
	VarTemperature      = "V_TEMPERATURE"
	VarText             = "V_TEXT"
	VarTripped          = "V_TRIPPED"
	VarUp               = "V_UP"
	VarUV               = "V_UV"
	VarVA               = "V_VA"
	VarVar              = "V_VAR"
	VarCustom           = "V_CUSTOM"
	VarCustom1          = "V_CUSTOM_1"
	VarCustom2          = "V_CUSTOM_2"
	VarCustom3          = "V_CUSTOM_3"
	VarCustom4          = "V_CUSTOM_4"
	VarCustom5          = "V_CUSTOM_5"
	VarVoltage          = "V_VOLTAGE"
	VarVolume           = "V_VOLUME"
	VarWatt             = "V_WATT"
	VarWeight           = "V_WEIGHT"
	VarWind             = "V_WIND"
)

// Internal messages
const (
	IntBatteryLevel          = "I_BATTERY_LEVEL"
	IntChildren              = "I_CHILDREN"
	IntConfig                = "I_CONFIG"
	IntDebug                 = "I_DEBUG"
	IntDiscoverRequest       = "I_DISCOVER_REQUEST"
	IntDiscoverResponse      = "I_DISCOVER_RESPONSE"
	IntFindParentRequest     = "I_FIND_PARENT_REQUEST"
	IntFindParentResponse    = "I_FIND_PARENT_RESPONSE"
	IntGatewayReady          = "I_GATEWAY_READY"
	IntHeartbeatRequest      = "I_HEARTBEAT_REQUEST"
	IntHeartbeatResponse     = "I_HEARTBEAT_RESPONSE"
	IntIDRequest             = "I_ID_REQUEST"
	IntIDResponse            = "I_ID_RESPONSE"
	IntInclusionMode         = "I_INCLUSION_MODE"
	IntLocked                = "I_LOCKED"
	IntLogMessage            = "I_LOG_MESSAGE"
	IntNodeName              = "I_NODE_NAME"
	IntNodeVersion           = "I_NODE_VERSION"
	IntNonceRequest          = "I_NONCE_REQUEST"
	IntNonceResponse         = "I_NONCE_RESPONSE"
	IntPing                  = "I_PING"
	IntPong                  = "I_PONG"
	IntPostSleepNotification = "I_POST_SLEEP_NOTIFICATION"
	IntPresentation          = "I_PRESENTATION"
	IntPreSleepNotification  = "I_PRE_SLEEP_NOTIFICATION"
	IntReboot                = "I_REBOOT"
	IntRegistrationRequest   = "I_REGISTRATION_REQUEST"
	IntRegistrationResponse  = "I_REGISTRATION_RESPONSE"
	IntSignalReportRequest   = "I_SIGNAL_REPORT_REQUEST"
	IntSignalReportResponse  = "I_SIGNAL_REPORT_RESPONSE"
	IntSignalReportReverse   = "I_SIGNAL_REPORT_REVERSE"
	IntSigningPresentation   = "I_SIGNING_PRESENTATION"
	IntTime                  = "I_TIME"
	IntVersion               = "I_VERSION"
)

// Data stream messages
const (
	StmFirmwareConfigRequest  = "ST_FIRMWARE_CONFIG_REQUEST"
	StmFirmwareConfigResponse = "ST_FIRMWARE_CONFIG_RESPONSE"
	StmFirmwareConfirm        = "ST_FIRMWARE_CONFIRM"
	StmFirmwareRequest        = "ST_FIRMWARE_REQUEST"
	StmFirmwareResponse       = "ST_FIRMWARE_RESPONSE"
	StmFirmwareResponseRLE    = "ST_FIRMWARE_RESPONSE_RLE"
	StmImage                  = "ST_IMAGE"
	StmSound                  = "ST_SOUND"
)
